---
- name: taolo
  hosts: all
  gather_facts: no
  tasks:
  - name: int
    ios_13_interface:
      name: loopback {{item.number}}
      ipv4: 10.0.{{item.number}.1/24}
      state: present
    with_items:
    - {number: 1}
    - {number: 2}
    - {number: 3}
