---
- name: tao lo
  hosts: all
  gather_facts: false
  tasks:
    name: int
    ios_sw:
      name: loopback {{item.number}}
      ipv4: 10.0{{item.number}.1/24}
      state: present
    with_item:
    - number: 1
    - number: 2
    - number: 3
